name: Build Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Gradle 7.6
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6

      - name: Grant execute permission for gradlew
        run: chmod +x ./chronobreak/gradlew

      - name: Build with Gradle
        run: cd chronobreak && ./gradlew build
